dist: trusty
language: php

before_script:
- phpenv config-rm xdebug.ini || return 0
- composer install

php:
  - 5.6
  - 7.1

script:
  - curl -L http://files.shopgate.com/travis-ci/php-cs-fixer.phar -o php-cs-fixer
  - chmod a+x php-cs-fixer
  - ./php-cs-fixer fix --config=.php-cs.dist --cache-file=.php-cs.cache --diff --dry-run --verbose .
  - rm php-cs-fixer
  - src/Backend/SgateShopgatePlugin/vendor/bin/phpunit
jobs:
  include:
  - stage: deploy
    php: 5.6
    before_script: skip
    script:
    - if [[ "$TRAVIS_TAG" ]]; then ./release/build_release_package.sh ; fi
    deploy:
      provider: releases
      api_key:
        secure: YcfW+zlmU2U1QqmxSG15G/llrppO/NQrYrROMp3Ta6jNjGoqz5/6SgvXeWIdfWP+3XffdpWbFob9wnQx7JVcxbaW+vNd/0f2/l3287kWrcgILo0bKra7ODHS/wdy5Md82KXhJqZBRlsHyDqUkqQdeWOdSqmWNFlLuyXl0eHc7sxcDqn/prxriYoTT77aqt3TVnolg0faTUmZofBS0J6zJIYZkA0pvjfCtwowY1Q5oDNfVYhoGhPlYaiYcu1x+aVlZIIwcG80kJEQtzU1Fp735yGnkhcEl5mXQGcVZMpXz0/MMhUmjpMcmrJE6oaM0J3/tUWgbSVcyQVT/qHeN5XU+LPnWAdDVt26fV3HTeRExAOTSV3J2ye1vPzAxxLeaYb0hYXxu15/eXsbjnBB+jFSwqnw9zSdTiLR0zpA2S45uBXL0HeCY4MhQ7fkdc6fMdzOEA8svoWoPBNwO7T7h5faDlb/gFY8awVjHL+H+HrycB09TXllRe+OhfhgqHy3JO1vVrF21F0XjnvGVptwB+pXeuB95+eOzmPfKB5efbHIufb0oiG3smBt9QXPtnLnADZqbePeyvTC1SbY5Jx1ZFzwuWQ5qqQXT3NLF4AjwgneamBUTaJTfzII62m9/unYYEummkyXpjDQ1xBxf+10VYr7wq/Igym7pJx9VvhE06tvGUg=
      file: shopgate-shopware-integration.zip
      skip_cleanup: true
      on:
        tags: true
